# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biPiO2xBww2euXi5cZxs7AvkRwqMypEK
"""

# Импортирем библиотеки
import yaml
import json

# Определяем функцию read_yaml, которая открывает файл из директории в переменной file_path
def read_yaml(file_path):
  # Открываем файл по указанному пути file_path в режиме чтения ('r').
  with open(file_path, 'r', encoding='utf-8') as my_file: # Указываем кодировку utf-8, чтобы корректно обработать текст на любых языках, включая кириллицу.
    data = yaml.load(my_file, Loader=yaml.FullLoader)
    return data

# Определяем функцию write_json, которая принимает данные из my_data и сохраняет в директории
def write_json(data, file_path):
  with open(file_path, 'w', encoding='utf-8') as my_file:
    json.dump(data, my_file, ensure_ascii=False, indent=4) # ensure_ascii=False сохраняет кириллицу, indent добавляет отступы по 4 пробела

if __name__ == "__main__":
  yaml_file = "/content/data_lab.yaml"  # Путь к YAML-файлу
  json_file = "/content/data_converted_lab.json"  # Путь для сохранения JSON-файла
  data = read_yaml(yaml_file)
  write_json(data, json_file)

